### ISSUE TITLE
Organize functions into modules

### ISSUE THREAD

**Issue by ccurtis7** [jingexu/cells-in-gel#4]
Great start to your functions! I suggest that you start thinking of a way to organize your functions into modules. You've seen this before in the `skimage` library e.g. `skimage.filters` and `skimage.morphology`, for instance.

To do this, move all your `.py` files into a single folder, I suggest `cells_in_gel`. Then store functions that fall into several broad categories into separate `.py` files with descriptive names such as `utils.py` for utility functions that are used throughout the project (e.g. function for loading datasets) or `preprocessing.py` .

**Comment by jennybennett** [comment]
Thanks for the suggestions! I have moved all of our initial functions (frequency_filter, phalloidin_488_binary, colorize, and sharpen_nuclei) to `preprocess.py` within the module `cells_in_gel`.

**Comment by jingexu** [comment]
invite Jenny to address this issue
