### ISSUE TITLE
Add use cases to `README.md`

### ISSUE THREAD

**Issue by ccurtis7** [jingexu/cells-in-gel#5]
It is useful to provide your reader with a quick list of use cases so they can directly decide whether they would want to use your code. A use case is a situation in which a software package could be used. Use cases for an ATM, for instance, would be to check your balance or to withdraw money.

**Comment by jingexu** [comment]
invite Irina to address this issue

**Comment by ikopyeva** [comment]
Resolved. I have added a few use cases and updated our README
