### ISSUE TITLE
Store development notebooks in a subfolder

### ISSUE THREAD

**Issue by ccurtis7** [jingexu/cells-in-gel#6]
I also suggest storing notebooks in which you develop code in a sub-folder. It's also a good idea to organize them by date, so you can name your notebooks something like `04_25_20_preprocessing_functions.ipynb`

**Comment by jingexu** [comment]
Good ideas! I have organized our notebooks by date and stored them in the subfolder `notebooks`.

**Comment by jingexu** [comment]
Invite jingexu to address this issue
